### ISSUE TITLE
[Bug] on python: BOCPD configured for BetaBernoulli fails in .step() function, 'x' object cannot be converted to 'PyBool'

### ISSUE THREAD

**Issue by HilaManor** [promised-ai/changepoint#5]
In the python library, initializing BOCPD using a beta bernoulli prior:
```python
cpd = chp.Bocpd(
    prior=chp.BetaBernoulli(),
    lam=30)
```
with some bernoulli sequence data
```python 
bers1 = np.random.binomial(1, 0.1, size=10000)
bers2 = np.random.binomial(1, 0.2, size=10000)
bers3 = np.random.binomial(1, 0.3, size=10000)
bers4 = np.random.binomial(1, 0.1, size=10000)
data = np.concatenate([bers1,bers2,bers3,bers4])
```

yields error when trying to update with the step function:
![image](https://github.com/promised-ai/changepoint/assets/53814901/4fe430cd-38f4-463c-a078-743c3a30f932)

The same happens when trying to cast to bool directly in python:
![image](https://github.com/promised-ai/changepoint/assets/53814901/a3316c2e-1804-4482-bcac-b240b44518b2)

**Comment by schmidmt** [comment]
Hey @HilaManor, thanks for reporting this.

I have a fix. I'll create a PR quickly here, but if you need a faster fix, you can change `cpd.step(x)` to `cpd.step(bool(x))`. The patch I'll release soon will fix the issue as well.

**Comment by HilaManor** [comment]
Thank you, the quick fix worked as well :)
